name: linux

on:
  push:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8 
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -c Release      
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
